# Generated by Django 3.1 on 2021-02-04 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inquiry', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='currency',
        ),
    ]
