# Generated by Django 3.1 on 2021-02-10 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiry', '0006_applicants'),
    ]

    operations = [
        migrations.AddField(
            model_name='career',
            name='index',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
