# Generated by Django 3.1 on 2021-02-10 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiry', '0007_career_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicants',
            name='date',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
