# Generated by Django 3.1 on 2021-02-10 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiry', '0008_applicants_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicants',
            name='resume',
            field=models.ImageField(blank=True, null=True, upload_to='resumes'),
        ),
    ]
