# Generated by Django 3.1 on 2021-02-10 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiry', '0011_designations'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Designations',
        ),
        migrations.AddField(
            model_name='applicants',
            name='status',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
