# Generated by Django 3.1 on 2021-02-10 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiry', '0012_auto_20210210_1733'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicants',
            name='status',
        ),
        migrations.AddField(
            model_name='career',
            name='status',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
