# Generated by Django 3.1 on 2021-02-11 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiry', '0013_auto_20210210_1748'),
    ]

    operations = [
        migrations.CreateModel(
            name='Free_Trial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
    ]
