# Generated by Django 3.1 on 2021-02-11 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiry', '0014_free_trial'),
    ]

    operations = [
        migrations.AddField(
            model_name='free_trial',
            name='date',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
