# Generated by Django 3.1 on 2021-02-02 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kriosk_main', '0002_auto_20210202_1545'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio_image',
            name='fk',
        ),
        migrations.DeleteModel(
            name='Portfolio',
        ),
        migrations.DeleteModel(
            name='Portfolio_Image',
        ),
    ]
