# Generated by Django 3.1 on 2021-02-02 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='image_side',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
