# Generated by Django 3.1 on 2021-02-02 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0002_auto_20210202_1613'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio',
            old_name='image_side',
            new_name='image_wide',
        ),
    ]
