# Generated by Django 3.1 on 2021-02-02 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0003_auto_20210202_1638'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio_image',
            old_name='image',
            new_name='image1',
        ),
    ]
