# Generated by Django 3.1 on 2021-02-03 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0005_home'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(blank=True, null=True)),
                ('service_name', models.CharField(blank=True, max_length=150, null=True)),
                ('service_name_slug', models.CharField(blank=True, max_length=150, null=True)),
                ('service_intro', models.TextField(blank=True, null=True)),
                ('service_detail', models.TextField(blank=True, null=True)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='service')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='service')),
                ('image_before', models.ImageField(blank=True, null=True, upload_to='service')),
                ('image_after', models.ImageField(blank=True, null=True, upload_to='service')),
            ],
        ),
        migrations.CreateModel(
            name='Service_Sub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('tiny_head', models.CharField(blank=True, max_length=250, null=True)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='service')),
                ('fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='panel.service')),
            ],
        ),
    ]
