# Generated by Django 3.1 on 2021-02-03 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0006_service_service_sub'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='sub_service_list',
            field=models.TextField(blank=True, null=True),
        ),
    ]
