# Generated by Django 3.1 on 2021-02-03 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0007_service_sub_service_list'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='sub_service_list',
            new_name='service_list',
        ),
    ]
