# Generated by Django 3.1 on 2021-02-04 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0008_auto_20210203_1913'),
    ]

    operations = [
        migrations.AddField(
            model_name='service_sub',
            name='detail',
            field=models.TextField(blank=True, null=True),
        ),
    ]
