# Generated by Django 3.1 on 2021-02-05 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0009_service_sub_detail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='services',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='service_advt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='service_advt_bool',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='service_bi',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='service_bi_bool',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='service_digital',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='service_digital_bool',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
