# Generated by Django 3.1 on 2021-02-11 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0011_meta'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Meta',
            new_name='Page',
        ),
    ]
