# Generated by Django 3.1 on 2021-02-11 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0012_auto_20210211_1212'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Page',
            new_name='Page_Handler',
        ),
    ]
