# Generated by Django 3.1 on 2021-02-11 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0015_auto_20210211_1325'),
    ]

    operations = [
        migrations.CreateModel(
            name='Our_Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('intro', models.TextField(blank=True, null=True)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='client')),
            ],
        ),
        migrations.CreateModel(
            name='Our_Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('intro', models.TextField(blank=True, null=True)),
                ('desg', models.CharField(blank=True, max_length=200, null=True)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='team')),
                ('sm1', models.BooleanField(blank=True, default=False, null=True)),
                ('sm1_icon', models.CharField(blank=True, max_length=100, null=True)),
                ('sm2', models.BooleanField(blank=True, default=False, null=True)),
                ('sm2_icon', models.CharField(blank=True, max_length=100, null=True)),
                ('sm3', models.BooleanField(blank=True, default=False, null=True)),
                ('sm3_icon', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
