# Generated by Django 3.1 on 2021-02-11 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0016_our_client_our_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='our_team',
            name='sm1_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='our_team',
            name='sm2_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='our_team',
            name='sm3_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
