# Generated by Django 3.1 on 2021-02-11 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0017_auto_20210211_1706'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Our_Client',
        ),
    ]
