# Generated by Django 3.1 on 2021-03-08 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0019_auto_20210215_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='service_inner',
            field=models.TextField(blank=True, null=True),
        ),
    ]
