# Generated by Django 3.1 on 2021-03-08 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0020_service_service_inner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='service_list',
        ),
    ]
