# Generated by Django 3.1 on 2021-02-01 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20210201_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auth_code',
            name='auth_code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
